### ISSUE TITLE
申请CF证书会卡死

### ISSUE THREAD

**Issue by ggrreeeedd** [yonggekkk/Hysteria-yg#2]
有成功，经常卡死

**Comment by yonggekkk** [comment]
> 有成功，经常卡死

卡哪？发图看看

**Comment by ggrreeeedd** [comment]
> > 有成就，常卡死
> 
> 卡哪？发图看看

是我网络环境问题,sorry，已经解决，另请教是否支持obfs，如何修改？官方是建议开启，有效防阻断

**Comment by yonggekkk** [comment]
脚本目前没加！
