### ISSUE TITLE
可否设置obfs? 

### ISSUE THREAD

**Issue by quan9364** [yonggekkk/Hysteria-yg#3]
最近udp封锁严重，不知道yg的脚本是否支持加入obfs混淆?

**Comment by yonggekkk** [comment]
我这没加。。没感觉封锁呀

**Comment by quan9364** [comment]
我这边上海电信封锁的挺严重，用移动蜂窝就没事JackyOn Aug 14, 2023, at 11:04, 甬哥侃侃侃ygkkk ***@***.***> wrote:﻿
我这没加。。没感觉封锁呀
