### ISSUE TITLE
同一vps，可否实现v4、v6分别搭建节点同时使用？

### ISSUE THREAD

**Issue by ypkin** [yonggekkk/Hysteria-yg#5]

**Comment by ypkin** [comment]
比如v6解锁流媒体好一些，用来看nf
而v4解锁流媒体不好，但翻墙速度较快，用来下载

**Comment by yonggekkk** [comment]
这个要分流了，目前没好办法

**Comment by ypkin** [comment]
> 这个要分流了，目前没好办法

甬哥，刚才我用你的脚本搭了v6，另一个人的脚本分别搭了v4，实现了v4 v6同时使用互不干扰！！！

**Comment by yonggekkk** [comment]
> > 这个要分流了，目前没好办法
> 
> 甬哥，刚才我用你的脚本搭了v6，另一个人的脚本搭了v4，实现了v4 v6同时使用互不干扰，开心！！

那就是两个HY各自运行了。。。
